[project]
name = "aia"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ag2[openai]>=0.8.1",
    "pydantic>=2.10.6",
    "requests>=2.32.3",
]

[project.scripts]
aia = "aia:run"
